export const commonActionTypes = {
    SET_SITE_LOGO : 'SET_SITE_LOGO',
    SET_SOCIAL_MEDIA : 'SET_SOCIAL_MEDIA',
    SET_FOOTER_LOGO_URL : 'SET_FOOTER_LOGO_URL',
    SET_FOOTER_CONTACT : 'SET_FOOTER_CONTACT',
    SET_ADDRESS : 'SET_ADDRESS',
    SET_FEATURED_RESTURANTS : 'SET_FEATURED_RESTURANTS',
}