export const wizardActionTypes = {
    SET_ACTIVE_STEP : 'SET_ACTIVE_STEP',
    SET_DONE_STEP : 'SET_DONE_STEP',
    REMOVE_DONE_STEPS : 'REMOVE_DONE_STEPS',
    SET_RESERVATION_TYPE : 'SET_RESERVATION_TYPE',
    SET_BOOKING_TYPE : 'SET_BOOKING_TYPE',
}